## 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zepn064b29mmgi9ifo.mysql.rds.aliyuncs.com:3306/jxzyyxb?zeroDateTimeBehavior=round&useSSL=true&useTimezone=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true
    username: jxzy
    password: Jxzytangliu001
  transaction:
    rollback-on-commit-failure: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    encoding: utf-8
    cache: false
    mode: LEGACYHTML5



  #redis
  redis:
    host: r-2zeau438goyxpelfa3pd.redis.rds.aliyuncs.com
    port: 6379
    database: 1
    password: Jxzy001!
## mybatis 配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
## 端口号设置
server:
  port: 8081
  max-http-header-size: 1024000
  #日志机别
  logging:
    level:
      root: info
#路径和域名获取
DOMAIN_NAME: https://topsroboteer.com.cn/

#腾讯短信验证
TENCENT_APPID: 1400295952
TENCENT_KEY: f4eeb442e910c057d2579c90fa0a3f4d
TENCENT_TEMPLATE: 500066
TENCENT_MINUTE: 5

#支付相关
#微信支付
wxpay:
  appid: wx99edc76989395ab4
  mchid: 1500030172
  apiSecretkey: b14558994cc99197ebb9f09d3d3eb09f
  depositCallbackInterface: https://topsroboteer.wang/system/smallAPP/wxRefundCallback
  wechatRefundRequest: https://api.mch.weixin.qq.com/secapi/pay/refund
  fileCertPath: /pro/Cert_Management/jxzy.p12
  certPath: /pro/Cert_Management/
  deposit_fileCertPath: /pro/Cert_Management/jxzy_deposit.p12
  deposit_weChat_mch_id: 1502139171

#支付宝支付
alipay:
  #支付宝小程序标识
  APP_ID: 2021002112625350
  #私钥
  MERCHANT_PRIVATE_KEY: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmwyt5aEuR7jBH/PVd7elOWjx3Jj9Um7H+kqKem7g96PwA+JDIqtUOpVs0YqjN3h3sbbcO1WvCXJECfv8zWCPnmI+csMCFS94WG/Od68AELONKBH1pVIw9RatqfIslyh+heBLWdQYtNI+gR8jVA76lrR9oEwHi1aznyjZDEVTZMncKuj3Mf2s6a4afQ6kbpR8+7a2Z37G5g0IImVGS+C2PW97DZwoQpU1GMdZVsaftdri69pS8rTbFWFZdAE8t3buZHc8S2ldjOgaH8z77OwyKshDgp4no2bX+ZMz6NiOUV1GHkixHsJnx9zBgT4u8rbv+L3j3U8yd5vYND+SdYgVnAgMBAAECggEAZ2SQesigOg084BVFKASO52ZpINKU52dU92qA6ufPVosyW4PBeLj6OgdpwdP9pw407Vak7cyC8FGmEq8cmP/n2vqq59Jquvpr6rdP1zTIq44NKeIYw4qJHKAqhG5Nc5ObAujIfTC3MKXq+swnB3M3686nr0ZBoBstBdVIyVJgkfyGDDflih4S5AmL4xwmJT2o4c9dTtGxNecUmFh/exTswOyzq0d1DQkaAGnPXFkPnTJXUXlVJoYXMGbqldM2J1WpaWYBu2oA7WnVp3ow8YtLUR+gsP5Ue4tzWFjQxQFTvxKjasq3eEbg72dE8ik7amJ4ptMdQ1SsklWm/cPzdnqSmQKBgQDu1l3QDjMRKeQ9MGdHzletcjKVh6Sn64fEdWRNy+gCx1lXx7aaBBrGqDTslg0LwMQ4KdBknc7YGl8QFFRie5Y+q8d2mzLRyNQZqFjBhnz1EmLORORrBzux7W8rymoeekgREjXHWNP/H7uj3bsnsj2HD+JS3p1zt/SOX0uWCtThIwKBgQCyvurkfcRIw2QjUYOLVciwr7Qs8WS6KKeJMkbDh6ETM0HI6ng+RgYpo/FijK1fvy+PVGqfybf1bLHSrM9OpMkBO6Qb/PoFqqkkinmORe+mlB6V0z4TAYwuMPoB8qOspKHYEoiaEEHmTaXaAeBEl5QK6Y1q59QkWO6l4QUl7TGI7QKBgFUJUiGPzLLhvXfj0gII/8KrlEMVJpT7ET3rpijk3tiObcsJOoSfzYDJxv4tdrumiLaOfLo2Tb03tn0dH+ZoplfuBXi/TVrQLGRuQhu1bKw9PZy/fqx0yNZS+XAYA6ySUTJyz18Iy4JcpAx2F/rMRYffKe/jfyACcTp3x4vGk4ENAoGAUqxLKHOjHaSB5HQHS6LZuB8MTt03oYK8OpCuejF5JtBGVQ9dni/1Gb1iIBrA9dAPx1NcHZvHIhSsCq0zFUTSU2eqd+eCHKzanrQNlOhz96/6lYGm7FOC6rpsaAo5+dgLo0yvMdLjKAox86t6dz9EkeeEKTYgwM8BUmfJYclbZ+ECgYAusbFFYTUV9sE2uCfj+jMcT0G+/Ckf5T+ao9h+rQLbPWN9q3o63mAk/9GQqMnllTcgoRDs2YNI8t/IUarNggkI+o08t7INQaKZZDgX7vxHjdFyt4IfQuWV/6+cPfvr85guvQ7Dnwsuci/m5UUDDVV2Q5vxRDHmHdVPvkyq0Tkv1g==
  #公钥
  ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAikc4ty51S4SnU5I4zeJLH51IzOb8Ox7YWJhNt+wZCQayUnnjZ7ETUIN/PU0dM1/QjqXLjvXq7oZem9jjaTc8dtxzTlKS569Vw8WVzO18jSBNZQGvLO42ZjjkYQLqrw6PzIUWTby8sfquo5MdFzP481he03NyHNRU7I3m2Ao4W2hxH09xogIndQGaV3Q+bQPQQaESamFFrMyUIyeDty8YnmEMN7QsvxcIrVnI4tuZNp99eXDE0SYqFKcKtBgRaSGEntx9U2MlX2JZeS2qwPIJWkBVn1kdQvX5RjnYza4yKuEsgSWkIfr0ZAh6bYri9mypBmHfRh4swsQl+IggcBM8qQIDAQAB
  #加密方式
  AES_SECRET_KEY: 4o/ScZAuZcopIHg6lZfx/w==
  #编码格式
  CHARSET: UTF-8
  #签名格式
  SIGN_TYPE: RSA2
  #签名格式
  FORMAT: json
  #支付宝接口地址
  PAY_URL: https://openapi.alipay.com/gateway.do
